
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include_dir_list automations/ 
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml
binary_sensor: !include binary_sensors.yaml 

hdmi_cec:
  devices:
    1: PS4

climate: !include climate.yaml

device_tracker: !include device_trackers.yaml
